In [1]:
print ("NORMALISASI")

NORMALISASI


In [2]:
def norm_feature(data):
    n_max = max(data)
    n_min = min(data)
    l_data  = len(data)
    
    for i in range (0,l_data):
        data[i] = (data[i] - n_min) / (n_max - n_min)
        
    return data

In [3]:
data = [10, 25, 15, 30, 50]

n_data = norm_feature(data)

n_data

[0.0, 0.375, 0.125, 0.5, 1.0]

In [4]:
import numpy as np
from sklearn.preprocessing import MinMaxScaler

In [5]:
data1 = [
    [100, 0.001],
    [8, 0.05],
    [50, 0.005],
    [88, 0.07],
    [4, 0.1]
]

np_data = np.asarray(data1)

print ("Dimensi dari data :")

print(np_data.shape)

print ("Artinya 5 Baris, 2 Kolom")

Dimensi dari data :
(5, 2)
Artinya 5 Baris, 2 Kolom


In [6]:
mm_scaler = MinMaxScaler()

mm_data = mm_scaler.fit_transform(data1)

print("Data Asli :")
print(np_data)
print("")
print("Data Setelah Normalisasi :")
print(mm_data)

Data Asli :
[[1.0e+02 1.0e-03]
 [8.0e+00 5.0e-02]
 [5.0e+01 5.0e-03]
 [8.8e+01 7.0e-02]
 [4.0e+00 1.0e-01]]

Data Setelah Normalisasi :
[[1.         0.        ]
 [0.04166667 0.49494949]
 [0.47916667 0.04040404]
 [0.875      0.6969697 ]
 [0.         1.        ]]


In [7]:
print ("STANDARISASI")

STANDARISASI


In [8]:
from statistics import mean, stdev

def std_feature(data):
    baris_data = data.shape[0]
    kolom_data = data.shape[1]
    
    for i in range (0, baris_data):
        for j in range (0,kolom_data):
            data[i][j] = (data[i][j] - mean(data[:,j])) / stdev(data[:,j])
    
    return data

In [9]:
data2 = [
    [100, 0.001],
    [8, 0.05],
    [50, 0.005],
    [88, 0.07],
    [4, 0.1]
]

np_data2 = np.asarray(data2)

std_data = std_feature(np_data2)

std_data

array([[ 1.13053908, -1.04102352],
       [-0.58585228,  0.43340554],
       [ 0.54596936,  0.16378374],
       [ 1.78715622,  0.2189989 ],
       [ 1.53764773,  0.21485145]])

In [10]:
from sklearn.preprocessing import StandardScaler

ss_scaler = StandardScaler()

std_data1 = ss_scaler.fit_transform(data2)

print("Data Setelah Standarisasi :")
print(std_data1)

Data Setelah Standarisasi :
[[ 1.26398112 -1.16389967]
 [-1.06174414  0.12639634]
 [ 0.         -1.05856939]
 [ 0.96062565  0.65304778]
 [-1.16286263  1.44302493]]


In [11]:
print("ENCODING")

ENCODING


In [12]:
from sklearn.preprocessing import OrdinalEncoder,OneHotEncoder

oe = [
    ['POLINEMA'],
    ['PENS'],
    ['PNJ'],
    ['PNP'],
    ['POLBAN'],
]

ord_oe = OrdinalEncoder().fit_transform(oe)

ohe_oe = OneHotEncoder().fit_transform(oe)

print ("Ordinal Encoding")
print(ord_oe)

print("")

print ("One Hot Encoding")
print(ohe_oe.toarray())

Ordinal Encoding
[[4.]
 [0.]
 [1.]
 [2.]
 [3.]]

One Hot Encoding
[[0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]]


In [13]:
print("TF-IDF")

TF-IDF


In [15]:
corpus = [
            'the house had a tiny little mouse',
            'the cat saw the mouse',
            'the mouse ran away from the house',
            'the cat finally ate the mouse',
            'the end of the mouse story'
]

In [18]:
sentence = 'The house had a little tiny mouse. The cat saw the mouse. The mouse ran away from the house'

stc_split = sentence.split('.')

stc_split

['The house had a little tiny mouse',
 ' The cat saw the mouse',
 ' The mouse ran away from the house']

In [29]:
from unittest import result
from sklearn.feature_extraction.text import TfidfVectorizer

vect = TfidfVectorizer(stop_words='english')

result = vect.fit_transform(corpus)

print(vect.get_feature_names())

print(result.toarray()[0])

print(result.todense())


['ate', 'away', 'cat', 'end', 'finally', 'house', 'little', 'mouse', 'ran', 'saw', 'story', 'tiny']
[0.         0.         0.         0.         0.         0.4755751
 0.58946308 0.28088232 0.         0.         0.         0.58946308]
[[0.         0.         0.         0.         0.         0.4755751
  0.58946308 0.28088232 0.         0.         0.         0.58946308]
 [0.         0.         0.58873218 0.         0.         0.
  0.         0.34771471 0.         0.72971837 0.         0.        ]
 [0.         0.58946308 0.         0.         0.         0.4755751
  0.         0.28088232 0.58946308 0.         0.         0.        ]
 [0.58946308 0.         0.4755751  0.         0.58946308 0.
  0.         0.28088232 0.         0.         0.         0.        ]
 [0.         0.         0.         0.67009179 0.         0.
  0.         0.31930233 0.         0.         0.67009179 0.        ]]
